language: ruby

install:
 - bundle install
 - gem install html-proofer -v '~> 3.8'

script:
 - bundle exec jekyll build
 - htmlproofer ./_site --disable-external --allow-hash-href

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: _site
  github-token: $GITHUB_TOKEN
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler
