language: ruby
bundler_args: --path $HOME/.bundle --with test
cache:
  directories:
    - $HOME/.bundle

script:
 - bundle exec jekyll build
 - bundle exec htmlproofer ./_site --disable-external --allow-hash-href

before_deploy
 - touch ./_site/.nojekyll

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: _site
  github-token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    recipients:
      - webmaster@mozilla.cz
    on_success: change
    on_failure: change

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
