dist: bionic
language: ruby
services:
  - docker

cache:
  directories:
    - vendor/.bundle
    - .jekyll-cache

script:
 - make build_in_docker

before_deploy:
 - touch _site/.nojekyll

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: _site
  github-token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    recipients:
    - webmaster@mozilla.cz
    on_success: change
    on_failure: always
