language: ruby

before_script:
 - gem install html-proofer -v '~> 3.8'

script:
 - bundle exec jekyll build
 - htmlproofer ./_site --disable-external --allow-hash-href

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: _site
  github-token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    recipients:
      - webmaster@mozilla.cz
    on_success: change
    on_failure: change

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler
