get_remote_data:
  - name: versions
    url: 'https://www.seamonkey-project.org/seamonkey_versions.json'
    type: json
  - name: ceskenoviny
    url: 'http://firefox-rss.ceskenoviny.cz/'
    type: rss
  - name: mozillacz
    url: 'https://www.mozilla.cz/feed/'
    type: rss

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

